### PR TITLE
run the ocr service in a docker container

### PR DESCRIPTION
**Pull request by leonardstruck**

### CODE REVIEW

**Review by BerniUtz — APPROVED** [review]
ich spreche kein docker aber es schaut sehr nach docker aus! Habe das auch mal gebaut und es hat gebaut 👍

**Comment by BerniUtz** [comment]
Ah wait der ocr-worker hat dann gefailed :(
image

**Comment by leonardstruck** [comment]
kannst du mal schauen ob RabbitMQ bei dir läuft?

**Comment by SirPoz** [comment]
Also ich bekommen einen Error in der rabbitMQ:

ws23-swkom-rabbitmq-1               | 2024-01-10 19:59:41.214493+00:00 [info] <0.778.0> accepting AMQP connection <0.778.0> (172.22.0.6:42986 -> 172.22.0.5:5672)
ws23-swkom-rabbitmq-1               | 2024-01-10 19:59:41.232499+00:00 [info] <0.778.0> connection <0.778.0> (172.22.0.6:42986 -> 172.22.0.5:5672): user 'rabbitmq' authenticated and granted access to vhost '/'
ws23-swkom-rabbitmq-1               | 2024-01-10 19:59:41.244039+00:00 [info] <0.792.0> accepting AMQP connection <0.792.0> (172.22.0.6:42990 -> 172.22.0.5:5672)
ws23-swkom-rabbitmq-1               | 2024-01-10 19:59:41.247712+00:00 [info] <0.792.0> connection <0.792.0> (172.22.0.6:42990 -> 172.22.0.5:5672): user 'rabbitmq' authenticated and granted access to vhost '/'
ws23-swkom-rabbitmq-1               | 2024-01-10 19:59:41.250324+00:00 [error] <0.801.0> Channel error on connection <0.792.0> (172.22.0.6:42990 -> 172.22.0.5:5672, vhost: '/', user: 'rabbitmq'), channel 1:
ws23-swkom-rabbitmq-1               | 2024-01-10 19:59:41.250324+00:00 [error] <0.801.0> operation queue.declare caused a channel exception not_found: no queue 'Microsoft.Extensions.Configuration.ConfigurationSection' in vhost '/'
ws23-swkom-rabbitmq-1               | 2024-01-10 19:59:41.259975+00:00 [info] <0.792.0> closing AMQP connection <0.792.0> (172.22.0.6:42990 -> 172.22.0.5:5672, vhost: '/', user: 'rabbitmq')
ws23-swkom-ocr_worker-1             | Queue Microsoft.Extensions.Configuration.ConfigurationSection exists
ws23-swkom-rabbitmq-1               | 2024-01-10 19:59:41.289373+00:00 [warning] <0.778.0> closing AMQP connection <0.778.0> (172.22.0.6:42986 -> 172.22.0.5:5672, vhost: '/', user: 'rabbitmq'):
ws23-swkom-rabbitmq-1               | 2024-01-10 19:59:41.289373+00:00 [warning] <0.778.0> client unexpectedly closed TCP connection

**Comment by leonardstruck** [comment]
Ist laut diesem Comment expected behaviour:

                // TODO: Rather than throwing an exception, the worker should wait for a message to be enqueued.

**Comment by leonardstruck** [comment]
https://github.com/BerniUtz/WS23-SWKOM/issues/38#issuecomment-1825825051

**Comment by BerniUtz** [comment]
image
RabbitMQ läuft. Minio sagt nur:
Added `minio` successfully.
mc: <ERROR> Unable to make bucket `minio/paperless`. Your previous request to create the named bucket succeeded and you already own it.

**Review by SirPoz — COMMENTED** [review]
Nimmst du hier die Postgres verknüpfung wieder aus dem OCR Worker heraus?

**Comment by BerniUtz** [comment]
Wo meinst du @SirPoz

**Comment by SirPoz** [comment]
siehe 
Screenshot 2024-01-10 221007

**Comment by BerniUtz** [comment]
> siehe Screenshot 2024-01-10 221007

yes Leo hat aber eh schon gemeint dass das wieder rein kommt vermutlich

**Pull request merged**
